[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "src/manifold/=lib/creator-core-solidity/contracts/",
    "@manifoldxyz/libraries-solidity/=lib/libraries-solidity/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
    "openzeppelin/=lib/openzeppelin-contracts/contracts"
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
